# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    time: 08:00:00 # time limit for each job
    cpus-per-task: 1
    mem:  8G
    output: results/logs/slurm-%x.%A.%a.log

trim_reads_with_fastp:
    cpus-per-task: 6
    mem:  48G
    cores: 6
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

align_reads_with_bwamem:
    cpus-per-task: 12
    mem:  96G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

mark_duplicates_with_picard:
    cpus-per-task: 1
    mem:  8G
    cores: 1
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

quality_filter_with_bamtools:
    cpus-per-task: 1
    mem:  8G
    cores: 1
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

blacklist_filter_with_bedtools:
    cpus-per-task: 1
    mem:  8G
    cores: 1
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

count_reads_in_RT_windows:
    cpus-per-task: 1
    mem:  8G
    cores: 1
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

merge_count_tables:
    cpus-per-task: 1
    mem:  8G
    cores: 1
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

merge_count_tables2:
    cpus-per-task: 1
    mem:  8G
    cores: 1
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

process_count_tables:
    cpus-per-task: 2
    mem:  16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bedgraphs:
    cpus-per-task: 2
    mem:  16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err
    
