experiment_name: "Frazer_ALL"
samples_table: "config/Samples.csv"
fastp_cpus: 6
bwa_cpus: 12
picard_memory: "8G"
bwa_genome: "/s/sansam-lab/2022Aug04_Frazer_Lab_ALL_RT_Processing/genome_index/GCF_000002035.6_GRCz11_primary_genomic.fna.gz"
bamtools_filter_mapQ: ">20"
bedtools_intersect_blacklist: "resources/Satellites.bed"
bedtools_intersect_greylist: "resources/HiCountWindows.bed"
RT_windows: "resources/RTWindows_danRer11_noAlts_ver01.bed"
max_insert_size: 1000

#################################################################
##                     Environment Modules                     ##
#################################################################
# These will be specific to your cluster                        #
#################################################################
fastp: "fastp/0.23.2"
bwa: "bwa/0.7.15"
samtools: "samtools/1.14"
picard: "picard/2.21.2"
bamtools: "bamtools/2.5.1"
bedtools: "bedtools/2.30.0"
R: "R/4.1.2-mkl"
Bioconductor: "bioconductor/3.14"
