experiment_name: "test"
samples_table: "config/testSamples.csv"
fastp_cpus: 6
bwa_cpus: 12
picard_memory: "8G"
bwa_genome: "/Volumes/hts_core/Shared/zebrafish/danRer11/noAlts/danRer11_noAlts.fa"
bamtools_filter_mapQ: ">10"
bedtools_intersect_blacklist: "resources/Satellites.bed"
bedtools_intersect_greylist: "resources/HiCountWindows.bed" 
RT_windows: "resources/RTWindows_danRer11_noAlts_ver01.bed"
